posts/blueprint.py
from flask import Blueprint, render_template


posts = Blueprint('posts', __name__, template_folder="templates")

@posts.route('/')
def index():
    return render_template('posts/index.html')

posts/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>

        {% block title %}

        {% endblock %} | Flask app

    </title>


</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href=" {{ url_for('index') }} ">Flask</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('posts.index') }}">Blog</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>


</nav>
  <div class = "container">
      <div class="row">
          <h1>
              {% block content_title %}

              {% endblock %}
          </h1>



      </div>

      {% block content %}

      {% endblock %}
  </div>


</body>
</html>

posts/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Mainpage
{% endblock %}

{% block content_title %}
    Mainpage
{% endblock %}

{% block content %}
   Mainpage content
{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
    Blueprint index page
{% endblock %}

{% block content_title %}
    Blueprint index page
{% endblock %}

{% block content %}
    Blueprint some content
{% endblock %}